version: 2

jobs:
  build:
    docker:
      - image: iserko/circle-test-ssh:v1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "PATH=$PATH"

workflows:
  version: 2.0
  build:
    jobs:
      - build
