version: 2

jobs:
  build:
    docker:
      - image: iserko/circle-test-ssh:v1
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - run: echo "PATH=$PATH"

workflows:
  version: 2
  build:
    jobs:
      - build
